package com.saga.common;

public enum TaskQueue {
    JIRA_ACTIVITY_TASK_QUEUE, SONAR_ACTIVITY_TASK_QUEUE, BUILDING_ACTIVITY_TASK_QUEUE, IADL_FULFILLMENT_WORKFLOW_TASK_QUEUE, TASK_ACTIVITY_TASK_QUEUE;
}
