spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sonar-service
workflow: IADLFulfillmentWorkflow
server:
  port: '8082'
application:
  name: build-svc
target: 127.0.0.1:7233
